# Simple Linear Regression Example
 

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression as Lr


In [ ]:
x = np.array([5,15,25,35,45,55]).reshape((-1,1))
y = np.array([5,20,14,32,22,38])


In [ ]:
print(x,x.shape)
print(y,y.shape)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]] (6, 1)
[ 5 20 14 32 22 38] (6,)


In [ ]:
model = Lr()

In [ ]:
model = model.fit(x,y)

In [ ]:
r_sq = model.score(x,y)
print(r_sq)

0.7158756137479542


In [ ]:
b1 = model.coef_
b0 = model.intercept_
print(f'y = {b1}[x] + {b0}')

y = [0.54][x] + 5.633333333333329


In [ ]:
x_predict = np.array([1,2,3,4,5,6]).reshape(-1 , 1)

In [ ]:
y_predict = model.predict(x_predict)
print(y_predict)

[6.17333333 6.71333333 7.25333333 7.79333333 8.33333333 8.87333333]


# Create Multiple Linear Regressoin

In [ ]:
multiple_linear = Lr()

In [ ]:
x2 = [
    [0, 1],
    [5, 1],
    [15, 2],
    [25, 5],
    [35, 11],
    [45, 15],
    [55, 34],
    [60, 35]
 ]

y2 =  [4, 5, 20, 14, 32, 22, 38, 43]
x2 , y2 = np.array(x2) , np.array(y2)

In [ ]:
multiple_linear = multiple_linear.fit(x2,y2) 

In [ ]:
b1 = multiple_linear.coef_
b0 = multiple_linear.intercept_
print(f'y = {b1}[x] + {b0}')

y = [0.44706965 0.25502548][x] + 5.52257927519819


# Polynomial Regression With scikit-learn


In [ ]:
from sklearn.preprocessing import PolynomialFeatures as Pf

In [ ]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [ ]:
transformer =  Pf(degree=2,include_bias=False)

In [ ]:
x_ = transformer.fit(x)

In [ ]:
x_ = transformer.transform(x)
# also use transformer.fit_transform()

In [ ]:
print('original x is :',x)
print('x_ is :',x_)

original x is : [[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
x_ is : [[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [ ]:
model = Lr().fit(x_,y)

In [ ]:
print(f'R^2 = {model.score(x_,y)}')
print(f'y = {model.coef_}[x]+ {model.intercept_}')

R^2 = 0.8908516262498563
y = [-1.32357143  0.02839286][x]+ 21.37232142857144


# Linear Regression With statsmodels
You can implement linear regression in Python by using the package statsmodels as well. Typically, this is desirable when you need more detailed results.

The procedure is similar to that of scikit-learn.

In [ ]:
 import statsmodels.api as sm

In [ ]:
print(x2)
print(y2)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]
[ 4  5 20 14 32 22 38 43]


In [ ]:
# for calaculate b0 in this methode should add constant number to x's vector
x2 = sm.add_constant(x2)
x2

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [ ]:
# create linear model with statsmodel
model = sm.OLS(y2,x2)

In [ ]:
results = model.fit()

In [ ]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Thu, 20 Oct 2022   Prob (F-statistic):            0.00713
Time:                        16:44:01   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:1542: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))
